### ISSUE TITLE
读取 Reality 配置文件，显示不是一个有效配置文件

### ISSUE THREAD

**Issue by Riverboat8865** [Kingtous/Fclash#70]
直接从CLASH-Verge拷贝了一个config.yml, 以下是最简单版本，但是显示不是有效文件。但是我删掉proxies，就没有问题。很奇怪，哪里出问题了。
```
external-controller: 127.0.0.1:22345

mixed-port: 22346


allow-lan: true
bind-address: '*'
mode: rule
log-level: info
dns:
    enable: true
    ipv6: false
    default-nameserver: [223.5.5.5, 119.29.29.29]
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query']
    fallback: ['https://doh.dns.sb/dns-query', 'https://dns.cloudflare.com/dns-query', 'https://dns.twnic.tw/dns-query', 'tls://8.8.4.4:853']
    fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }


proxies:
    - { name: 'XXXX', type: vless, server: 46.18.159.115, port: 443, uuid: 52132137c-b121-4c8a-b6a3-c6f232213237e, flow: xtls-rprx-vision, client-fingerprint: chrome, udp: true, tls: true, servername: google.com, reality-opts: { public-key: aacpTbk123213213213GgpblajM, short-id: 7f1421310 } }
    
rules:
  # localhost rule
  - DOMAIN-KEYWORD,announce,DIRECT
  - DOMAIN-KEYWORD,torrent,DIRECT
  - DOMAIN-KEYWORD,tracker,DIRECT
  - DOMAIN-SUFFIX,smtp,DIRECT
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
```
